### PR TITLE
Please create arrays.xml for Slovak language

### PR DESCRIPTION
**Pull request by ja-som**

### CODE REVIEW

**Comment by leorigna** [comment]
what do you mean?

**Comment by ja-som** [comment]
I don't understand, what, what I mean? :)
I have translated strings and arrays for Slovak language.

**Comment by leorigna** [comment]
theme are not used! :)

**Comment by ja-som** [comment]
I know, but I was thinking that maybe sometimes in the future you will add them, when there are in arrays :)
Can you then please merge strings.xml?
Thanks

**Pull request merged**
